config/routes.rb
AmoebaCircus::Application.routes.draw do
  resources :acts

  resources :amoebas
  
  get 'amoebas/:id/split' => 'amoebas#split', as: :split
  post 'amoebas/split' => 'amoebas#splitter'

  root 'dashboard#index'

end

app/models/act.rb
class Act < ActiveRecord::Base
  has_many :act_amoebas
  has_many :amoebas, :through => :act_amoebas

  def amoeba_ids=(amoeba_ids)
    amoeba_ids.each do |amoeba_id|
      self.act_amoebas.build(:amoeba_id => amoeba_id)
    end
  end
end

app/models/act_amoeba.rb
class ActAmoeba < ActiveRecord::Base
  belongs_to :amoeba
  belongs_to :act
end

app/models/amoeba.rb
class Amoeba < ActiveRecord::Base
  belongs_to :talent
  
  has_many :act_amoebas
  has_many :acts, :through => :act_amoebas
end

app/models/talent.rb
class Talent < ActiveRecord::Base
  has_many :amoebas
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController
  before_action :set_act, only: [:show, :edit, :update, :destroy]

  # GET /acts
  # GET /acts.json
  def index
    @acts = Act.all
  end

  # GET /acts/1
  # GET /acts/1.json
  def show
  end

  # GET /acts/new
  def new
    @act = Act.new
    @amoebas = Amoeba.all
  end

  # GET /acts/1/edit
  def edit
    @amoebas = Amoeba.all
  end

  # POST /acts
  # POST /acts.json
  def create
    @act = Act.new(act_params)

    respond_to do |format|
      if @act.save
        format.html { redirect_to @act, notice: 'Act was successfully created.' }
        format.json { render action: 'show', status: :created, location: @act }
      else
        format.html { render action: 'new' }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acts/1
  # PATCH/PUT /acts/1.json
  def update
    respond_to do |format|
      if @act.update(act_params)
        format.html { redirect_to @act, notice: 'Act was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acts/1
  # DELETE /acts/1.json
  def destroy
    @act.destroy
    respond_to do |format|
      format.html { redirect_to acts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_act
      @act = Act.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def act_params
      params.require(:act).permit(:name, :performance_date, :amoeba_ids => []) 
    end
end

app/controllers/amoebas_controller.rb
class AmoebasController < ApplicationController
  before_action :set_amoeba, only: [:show, :edit, :update, :split, :splitter, :destroy]

  # GET /amoebas
  # GET /amoebas.json
  def index
    @amoebas = Amoeba.all
  end

  # GET /amoebas/1
  # GET /amoebas/1.json
  def show
  end

  # GET /amoebas/new
  def new
    @amoeba = Amoeba.new
    @talents = Talent.all
    @acts = Act.all
  end

  # GET /amoebas/1/edit
  def edit
    @talents = Talent.all
    @acts = Act.all
  end

  # POST /amoebas
  # POST /amoebas.json
  def create
    @amoeba = Amoeba.new(amoeba_params)
    
    respond_to do |format|
      if @amoeba.save
        format.html { redirect_to @amoeba, notice: 'Amoeba was successfully created.' }
        format.json { render action: 'show', status: :created, location: @amoeba }
      else
        format.html { render action: 'new' }
        format.json { render json: @amoeba.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amoebas/1
  # PATCH/PUT /amoebas/1.json
  def update
    respond_to do |format|
      if @amoeba.update(amoeba_params)
        format.html { redirect_to @amoeba, notice: 'Amoeba was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @amoeba.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amoebas/1
  # DELETE /amoebas/1.json
  def destroy
    @amoeba.destroy
    respond_to do |format|
      format.html { redirect_to amoebas_url }
      format.json { head :no_content }
    end
  end

  # GET /amoebas/1/split
  def split
  end

  # POST /amoebas/split
  def splitter
    gen = params[:generation].to_i + 1

    amoeba_1 = Amoeba.new
    amoeba_1.name = params[:name_1]
    amoeba_1.talent_id = params[:talent_id]
    amoeba_1.generation = gen
    amoeba_1.save

    amoeba_2 = Amoeba.new
    amoeba_2.name = params[:name_2]
    amoeba_2.talent_id = params[:talent_id]
    amoeba_2.generation = gen
    amoeba_2.save

    @amoeba.destroy
    redirect_to amoebas_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amoeba
      @amoeba = Amoeba.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amoeba_params
      params.require(:amoeba).permit(:name, :generation, :talent_id, :act_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @amoebas = Amoeba.all
    @acts = Act.all
  end
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/amoebas_helper.rb
module AmoebasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/acts/_form.html.erb
<%= form_for(@act) do |f| %>
  <% if @act.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@act.errors.count, "error") %> prohibited this act from being saved:</h2>

      <ul>
      <% @act.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :performance_date %><br>
    <%= f.datetime_select :performance_date %>
  </div>
  <div class="field">
    <%= f.label :amoebas %><br>
    <%= f.collection_check_boxes(:amoeba_ids, @amoebas, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acts/edit.html.erb
<h1>Editing act</h1>

<%= render 'form' %>

<%= link_to 'Show', @act %> |
<%= link_to 'Back', acts_path %>

app/views/acts/index.html.erb
<h1>Listing acts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Performance date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @acts.each do |act| %>
      <tr>
        <td><%= act.name %></td>
        <td><%= act.performance_date %></td>
        <td><%= link_to 'Show', act %></td>
        <td><%= link_to 'Edit', edit_act_path(act) %></td>
        <td><%= link_to 'Destroy', act, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Act', new_act_path %>

app/views/acts/new.html.erb
<h1>New act</h1>

<%= render 'form' %>

<%= link_to 'Back', acts_path %>

app/views/acts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @act.name %>
</p>

<p>
  <strong>Performance date:</strong>
  <%= @act.performance_date %>
</p>

<p>
  <strong>Amoebas Performing:</strong>
  <ul>
    <% @act.amoebas.each do |amoeba| %>
      <li><%= link_to amoeba.name, amoeba_path(amoeba) %></li>
    <% end %>
  </ul>
</p>

<hr>

<%= link_to 'Edit', edit_act_path(@act) %> |
<%= link_to 'Back', acts_path %>

app/views/amoebas/_form.html.erb
<%= form_for(@amoeba) do |f| %>
  <% if @amoeba.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@amoeba.errors.count, "error") %> prohibited this amoeba from being saved:</h2>

      <ul>
      <% @amoeba.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :generation %><br>
    <%= f.number_field :generation %>
  </div>
  <div class="field">
    <%= f.label :talent_id %><br>
    <%= f.collection_radio_buttons(:talent_id, @talents, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :acts %><br>
    <%= f.collection_check_boxes(:act_ids, @acts, :id, :name) %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/amoebas/edit.html.erb
<h1>Editing amoeba</h1>

<%= render 'form' %>

<%= link_to 'Show', @amoeba %> |
<%= link_to 'Back', amoebas_path %>

app/views/amoebas/index.html.erb
<h1>Listing amoebas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Generation</th>
      <th>Talent</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @amoebas.each do |amoeba| %>
      <tr>
        <td><%= amoeba.name %></td>
        <td><%= amoeba.generation %></td>
        <td><%= amoeba.talent.name %></td>
        <td><%= link_to 'Show', amoeba %></td>
        <td><%= link_to 'Edit', edit_amoeba_path(amoeba) %></td>
        <td><%= link_to 'Destroy', amoeba, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amoeba', new_amoeba_path %>

app/views/amoebas/new.html.erb
<h1>New amoeba</h1>

<%= render 'form' %>

<%= link_to 'Back', amoebas_path %>

app/views/amoebas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @amoeba.name %>
</p>

<p>
  <strong>Generation:</strong>
  <%= @amoeba.generation %>
</p>

<p>
  <strong>Talent:</strong>
  <%= @amoeba.talent.name %>
</p>

<p>
  <strong>Acts:</strong>
  <ul>
    <% @amoeba.acts.each do |act| %>
      <li><%= link_to act.name, act_path(act) %></li>
    <% end %>
  </ul>
</p>

<hr>
<%= link_to 'Split', split_path(@amoeba) %> |
<%= link_to 'Edit', edit_amoeba_path(@amoeba) %> |
<%= link_to 'Back', amoebas_path %>

app/views/amoebas/split.html.erb
<h1>Split <%= @amoeba.name %></h1>

<%= form_tag "/amoebas/split", :method => "post" do %>
  <input type="hidden" name="id" value="<%= @amoeba.id %>">
  <input type="hidden" name="generation" value="<%= @amoeba.generation %>">
  <input type="hidden" name="talent_id" value="<%= @amoeba.talent_id %>">
  <div class="field">
    <label for="amoeba_1">Amoeba 1</label>
    <input type="text" id="amoeba_1" name="name_1"><br>
  </div>
  <div class="field">
    <label for="amoeba_2">Amoeba 2</label>
    <input type="text" id="amoeba_2" name="name_2"><br>
  </div>
  <div class="actions">
    <input type="submit" value="split">
  </div>
<% end %>

<%= link_to 'Back', amoebas_path %>

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>
<div>
  <h2>Amoebas</h2>
  <ul>
    <% @amoebas.each do |amoeba| %>
      <li><%= link_to amoeba.name, amoeba_path(amoeba) %></li>
    <% end %>
  </ul>
</div>

<div>
  <h2>Acts</h2>
  <ul>
    <% @acts.each do |act| %>
      <li><%= link_to act.name, act_path(act) %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmoebaCircus</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <%= link_to 'Home', root_path %> | 
    <%= link_to 'Amoebas', amoebas_path %> | 
    <%= link_to 'Acts', acts_path %>
  </nav>
<%= yield %>

</body>
</html>